from django.conf.urls import patterns, include, url
from console.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'judy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^test/$', test),
    url(r'^$', index),
    url(r'^login/', login),
    url(r'^logout/', logout),
    url(r'^server_apply/$', server_apply),
    url(r'^config/add/$', config_add),
    url(r'^config/list/$', config_list),
    url(r'^config/edit/(\d*)/$', config_edit),
    url(r'^config/delete/$', config_delete),
    url(r'^review/$', review),
    url(r'^review/checked/$', review_checked),
    url(r'^review/reject/$', review_reject),
    url(r'^host/manage/$', host_manage),
    url(r'^host/add/$', host_add),
    url(r'^host/host_moni/$', host_moni),
    url(r'^host/edit/(\d*)/$', host_edit),
    url(r'^host/delete/$', host_delete),
    url(r'^container/manage/$', container_manage),
    url(r'^container/ActionLogs/$', auditLogs_manage),
    #url(r'^container_manage/$', users_container_manage),
    url(r'^container/start/$', container_start),
    url(r'^container/stop/$', container_stop),
    url(r'^container/delete/$', container_delete),
    url(r'^container/reset/$', container_reset),
    url(r'^container/detail/(\d*)/$', container_detail),
    url(r'^container/batch_handle/$', container_batch_handle),
    url(r'^user/manage/$', user_manage),
    url(r'^user/add/$', user_add),
    url(r'^user/edit/(\d*)/$', user_edit),
    url(r'^user/delete/$', user_delete),
    url(r'^application/detail/(\d*)/$', application_detail),
    url(r'^application/retry/$', application_retry),
    url(r'^monitor/$', monitor),
    url(r'^monitor/(.*)/$', monitor_host),
    url(r'^get_data/$', get_data),
    url(r'^get_dynamic/$', get_dynamic_data),
)
